// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Read_EDI_Data.Data;

namespace Read_EDI_Data.Migrations
{
    [DbContext(typeof(Read_EDI_DataContext))]
    partial class Read_EDI_DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Read_EDI_Data.Models.Ports", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Big")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("N1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("N3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("N4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ST")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ports");
                });
#pragma warning restore 612, 618
        }
    }
}
